pub mod error;
pub mod autograd;
pub mod module;
pub mod nn;
pub mod loss;
pub mod optim;
pub mod lr_scheduler;
pub mod init;
pub mod grad;
pub mod checkpoint;
pub mod zoo;
pub mod trainer;
pub mod metrics;
pub mod data;
pub mod transforms;
pub mod serialize;

pub use error::{NnError, NnResult};
pub use autograd::{ADTensor, TensorId, startRecording, stopRecording, isRecording, backward as autograd_backward};
pub use module::{Module, Parameter, Buffer, Sequential, ModuleList, TrainingMode};
pub use nn::*;
pub use loss::*;
pub use optim::Optimizer;
pub use lr_scheduler::{LRScheduler, SchedulerType};
pub use trainer::{Trainer, TrainingConfig, TrainingState, Metric, Callback, EarlyStopping};
pub use metrics::*;
pub use data::{DataLoader, Dataset, TensorDataset};
pub use checkpoint::{Checkpoint, CheckpointManager, CheckpointMetadata};
pub use zoo::{ModelRegistry, ModelInfo, DownloadManager};
pub use serialize::{save_model_weights, load_model_weights, save_model_json, load_model_json};
