//! Health monitor with heartbeat, metrics, health status, alerts, and self-diagnostics.

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::config::HealthConfig;

/// Unique identifier for a monitored component.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MonitorId(pub Uuid);

impl MonitorId {
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for MonitorId {
    fn default() -> Self {
        Self::new()
    }
}

/// Health status of a component.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum HealthStatus {
    Healthy,
    Degraded,
    Unhealthy,
    Unknown,
}

impl HealthStatus {
    /// Whether the component is operational.
    pub fn is_operational(&self) -> bool {
        matches!(self, Self::Healthy | Self::Degraded)
    }
}

impl std::fmt::Display for HealthStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Healthy => write!(f, "healthy"),
            Self::Degraded => write!(f, "degraded"),
            Self::Unhealthy => write!(f, "unhealthy"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

/// Heartbeat record for a component.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Heartbeat {
    pub component_id: MonitorId,
    pub timestamp_ms: u64,
    pub status: HealthStatus,
    pub message: Option<String>,
    pub metrics: HashMap<String, f64>,
}

/// Alert severity level.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
}

impl std::fmt::Display for AlertSeverity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Info => write!(f, "info"),
            Self::Warning => write!(f, "warning"),
            Self::Critical => write!(f, "critical"),
        }
    }
}

/// An alert generated by the health monitor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub id: Uuid,
    pub component_id: MonitorId,
    pub severity: AlertSeverity,
    pub message: String,
    pub timestamp_ms: u64,
    pub acknowledged: bool,
}

/// Health metrics snapshot for a component.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ComponentMetrics {
    pub uptime_ms: u64,
    pub heartbeat_count: u64,
    pub last_heartbeat_ms: u64,
    pub error_count: u64,
    pub request_count: u64,
    pub avg_response_time_ms: f64,
    pub custom: HashMap<String, f64>,
}

/// Health record for a monitored component.
#[derive(Debug, Clone)]
pub struct ComponentHealth {
    pub id: MonitorId,
    pub name: String,
    pub status: HealthStatus,
    pub metrics: ComponentMetrics,
    pub last_check_ms: u64,
}

/// Self-diagnostic result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagnosticResult {
    pub component: String,
    pub status: HealthStatus,
    pub message: String,
    pub duration_ms: u64,
}

/// Health monitor tracking heartbeats, metrics, alerts, and self-diagnostics.
pub struct HealthMonitor {
    components: RwLock<HashMap<MonitorId, ComponentHealth>>,
    alerts: RwLock<Vec<Alert>>,
    config: HealthConfig,
    running: AtomicBool,
    stats: RwLock<HealthStatistics>,
}

/// Health monitor statistics.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HealthStatistics {
    pub total_heartbeats: u64,
    pub total_alerts: u64,
    pub components_monitored: usize,
    pub healthy_components: usize,
    pub unhealthy_components: usize,
}

impl HealthMonitor {
    /// Create a new health monitor.
    pub fn new(config: HealthConfig) -> Self {
        Self {
            components: RwLock::new(HashMap::new()),
            alerts: RwLock::new(Vec::new()),
            config,
            running: AtomicBool::new(true),
            stats: RwLock::new(HealthStatistics::default()),
        }
    }

    /// Register a component for health monitoring.
    pub fn register(&self, name: impl Into<String>) -> MonitorId {
        let id = MonitorId::new();
        let now = now_ms();
        let health = ComponentHealth {
            id,
            name: name.into(),
            status: HealthStatus::Unknown,
            metrics: ComponentMetrics::default(),
            last_check_ms: now,
        };
        self.components.write().insert(id, health);
        id
    }

    /// Record a heartbeat from a component.
    pub fn heartbeat(&self, id: MonitorId, status: HealthStatus, message: Option<String>) {
        let now = now_ms();
        let mut components = self.components.write();
        if let Some(health) = components.get_mut(&id) {
            let was_unhealthy = !health.status.is_operational();
            health.status = status;
            health.last_check_ms = now;
            health.metrics.heartbeat_count += 1;
            health.metrics.last_heartbeat_ms = now;

            if was_unhealthy && status.is_operational() {
                self.alerts.write().push(Alert {
                    id: Uuid::new_v4(),
                    component_id: id,
                    severity: AlertSeverity::Info,
                    message: format!("component '{}' recovered", health.name),
                    timestamp_ms: now,
                    acknowledged: false,
                });
            }
        }
        self.stats.write().total_heartbeats += 1;
    }

    /// Check whether a component has timed out (no heartbeat within threshold).
    pub fn check_timeouts(&self) -> Vec<MonitorId> {
        let now = now_ms();
        let timeout = self.config.heartbeat_timeout_ms;
        let mut timed_out = Vec::new();

        for (id, health) in self.components.read().iter() {
            if health.status.is_operational() && now - health.last_check_ms > timeout {
                timed_out.push(*id);
                self.alerts.write().push(Alert {
                    id: Uuid::new_v4(),
                    component_id: *id,
                    severity: AlertSeverity::Warning,
                    message: format!(
                        "component '{}' heartbeat timeout ({}ms since last)",
                        health.name,
                        now - health.last_check_ms
                    ),
                    timestamp_ms: now,
                    acknowledged: false,
                });
            }
        }

        timed_out
    }

    /// Get the health status of a component.
    pub fn status(&self, id: MonitorId) -> Option<HealthStatus> {
        self.components.read().get(&id).map(|h| h.status)
    }

    /// Get full health information for a component.
    pub fn component_health(&self, id: MonitorId) -> Option<ComponentHealth> {
        self.components.read().get(&id).cloned()
    }

    /// Get all active (unacknowledged) alerts.
    pub fn active_alerts(&self) -> Vec<Alert> {
        self.alerts
            .read()
            .iter()
            .filter(|a| !a.acknowledged)
            .cloned()
            .collect()
    }

    /// Acknowledge an alert.
    pub fn acknowledge_alert(&self, alert_id: Uuid) -> bool {
        let mut alerts = self.alerts.write();
        if let Some(alert) = alerts.iter_mut().find(|a| a.id == alert_id) {
            alert.acknowledged = true;
            true
        } else {
            false
        }
    }

    /// Run self-diagnostics on all registered components.
    pub fn self_diagnostics(&self) -> Vec<DiagnosticResult> {
        let mut results = Vec::new();
        let components = self.components.read();

        for (_, health) in components.iter() {
            let start = Instant::now();
            let status = if health.metrics.error_count == 0 {
                HealthStatus::Healthy
            } else if health.metrics.error_count < 10 {
                HealthStatus::Degraded
            } else {
                HealthStatus::Unhealthy
            };
            let elapsed = start.elapsed().as_millis() as u64;

            results.push(DiagnosticResult {
                component: health.name.clone(),
                status,
                message: format!(
                    "errors: {}, requests: {}, avg_response: {:.2}ms",
                    health.metrics.error_count,
                    health.metrics.request_count,
                    health.metrics.avg_response_time_ms
                ),
                duration_ms: elapsed,
            });
        }

        results
    }

    /// Get a summary of all component health statuses.
    pub fn summary(&self) -> HashMap<HealthStatus, usize> {
        let mut summary = HashMap::new();
        for health in self.components.read().values() {
            *summary.entry(health.status).or_insert(0) += 1;
        }
        summary
    }

    /// Get statistics.
    pub fn statistics(&self) -> HealthStatistics {
        let mut stats = self.stats.read().clone();
        let components = self.components.read();
        stats.components_monitored = components.len();
        stats.healthy_components = components
            .values()
            .filter(|h| h.status == HealthStatus::Healthy)
            .count();
        stats.unhealthy_components = components
            .values()
            .filter(|h| h.status == HealthStatus::Unhealthy)
            .count();
        stats.total_alerts = self.alerts.read().len() as u64;
        stats
    }

    /// Shut down the health monitor.
    pub fn shutdown(&self) {
        self.running.store(false, Ordering::Relaxed);
    }
}

impl Default for HealthMonitor {
    fn default() -> Self {
        Self::new(HealthConfig::default())
    }
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_component() {
        let monitor = HealthMonitor::new(HealthConfig::default());
        let id = monitor.register("test-service");
        assert!(monitor.status(id).is_some());
        assert_eq!(monitor.status(id).unwrap(), HealthStatus::Unknown);
    }

    #[test]
    fn heartbeat_updates_status() {
        let monitor = HealthMonitor::new(HealthConfig::default());
        let id = monitor.register("svc");

        monitor.heartbeat(id, HealthStatus::Healthy, None);
        assert_eq!(monitor.status(id).unwrap(), HealthStatus::Healthy);
    }

    #[test]
    fn heartbeat_generates_alert_on_recovery() {
        let monitor = HealthMonitor::new(HealthConfig::default());
        let id = monitor.register("svc");

        monitor.heartbeat(id, HealthStatus::Unhealthy, Some("down".to_string()));
        assert!(monitor.active_alerts().is_empty());

        monitor.heartbeat(id, HealthStatus::Healthy, Some("recovered".to_string()));
        let alerts = monitor.active_alerts();
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].severity, AlertSeverity::Info);
    }

    #[test]
    fn acknowledge_alert() {
        let monitor = HealthMonitor::new(HealthConfig::default());
        let id = monitor.register("svc");

        monitor.heartbeat(id, HealthStatus::Unhealthy, None);
        monitor.heartbeat(id, HealthStatus::Healthy, None);

        let alerts = monitor.active_alerts();
        assert_eq!(alerts.len(), 1);
        monitor.acknowledge_alert(alerts[0].id);
        assert!(monitor.active_alerts().is_empty());
    }

    #[test]
    fn self_diagnostics() {
        let monitor = HealthMonitor::new(HealthConfig::default());
        monitor.register("a");
        monitor.register("b");

        let results = monitor.self_diagnostics();
        assert_eq!(results.len(), 2);
    }

    #[test]
    fn summary() {
        let monitor = HealthMonitor::new(HealthConfig::default());
        let id1 = monitor.register("a");
        let id2 = monitor.register("b");

        monitor.heartbeat(id1, HealthStatus::Healthy, None);
        monitor.heartbeat(id2, HealthStatus::Unhealthy, None);

        let summary = monitor.summary();
        assert_eq!(summary[&HealthStatus::Healthy], 1);
        assert_eq!(summary[&HealthStatus::Unhealthy], 1);
    }

    #[test]
    fn statistics() {
        let monitor = HealthMonitor::new(HealthConfig::default());
        let id = monitor.register("svc");
        monitor.heartbeat(id, HealthStatus::Healthy, None);

        let stats = monitor.statistics();
        assert_eq!(stats.components_monitored, 1);
        assert_eq!(stats.total_heartbeats, 1);
    }

    #[test]
    fn health_status_operational() {
        assert!(HealthStatus::Healthy.is_operational());
        assert!(HealthStatus::Degraded.is_operational());
        assert!(!HealthStatus::Unhealthy.is_operational());
        assert!(!HealthStatus::Unknown.is_operational());
    }
}
