apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - deployment.yml

namespace: neo
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: neo-agi
