apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: neo-executive
    patch: |
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "8"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "16Gi"
  - target:
      kind: PersistentVolumeClaim
      name: neo-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 200Gi
